import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:news_project/api/api_constants.dart';
import 'package:news_project/api/end_points.dart';
import 'package:news_project/model/news_responce.dart';
import 'package:news_project/model/source_responce.dart';

class ApiManager {
  //function to give me news sources
  /*
     https://newsapi.org/v2/top-headlines/sources?
     apiKey=fd291a1579744ea686a81bdf53b1f02c
     */
  static Future<SourceResponce?> getSources() async{
    Uri url = Uri.http(ApiConstants.baseUrl ,
    EndPoints.sourceApi,{
       'apiKey' : ApiConstants.apiKey
        });
    try{
      var responce =await http.get(url);
      //String => json => object
      var bodyString = responce.body ; //String
      var json = jsonDecode(bodyString); // json
      return SourceResponce.fromJson(json); //object

      //to sum up the last 3 lines
      //Autogenerated.fromJson(jsonDecode(responce.body)); //object
    }catch(e){
      throw e;
    }
  }

  /*
  https://newsapi.org/v2/everything?q=bitcoin&
  apiKey=fd291a1579744ea686a81bdf53b1f02c
  */

static Future<NewsResponce?> getNewsBySourceId(String sourceId)async{
  Uri url = Uri.https(ApiConstants.baseUrl,
  EndPoints.newsApi,
  {
    'apiKey': ApiConstants.apiKey,
    'sources': sourceId
  });
try{
  var responce = await http.get(url);
  var responceBody = responce.body;
  var json = jsonDecode(responceBody);
  return NewsResponce.fromJson(json);
}catch(e){
  throw e;
}

}
}
